spring:
  profiles:
    active: local
      #?? ????? ???? ???? ???
    group:
      local:
        - common
      prod:
        - common

#?? ?????? ??? - group

---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost::3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: localhost
      port : 6379 #default port
  jpa:
    hibernate:
      ddl-auto: create #only in develope enviroment (b.o table drop)
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod

